--Elaborar una tabla de los clientes con solo préstamo hipotecario,  mostrando  código contrato, 
--la agencia, edad, sexo, el desembolso de préstamo, saldo Pasivo y saldo Activo.

--1 Identificar tablas:
SELECT*FROM [dbo].[TB_CLIENTE_PERFIL]
SELECT * FROM [dbo].[TB_CLIENTE_PRESTAMOS]
SELECT * FROM [dbo].[TB_CLIENTE_RENTABILIDAD]
SELECT * FROM [dbo].[TB_CLIENTE_PRODUCTOS]
SELECT * FROM [dbo].[TB_TIPO_PRESTAMO]
--2 Tipo de Join: INNER JOIN

--3 Condicion: SOLO PRESTAMO HIPOTECARIO

--4 EXTRAER DATA:
SELECT T2.CONTRATO,T1.CODIGO,T1.COD_AGENCIA,T1.SEXO,DATEDIFF(YEAR,T1.FH_NACIMIENTO,GETDATE()) AS EDAD,T3.SALDO_ACTIVO,T3.SALDO_PASIVO, T2.DESEMBOLSO 
FROM [dbo].[TB_CLIENTE_PERFIL] T1 
INNER JOIN [dbo].[TB_CLIENTE_PRESTAMOS] T2 ON T1.CODIGO = T2.CODIGO
INNER JOIN [dbo].[TB_CLIENTE_RENTABILIDAD] T3 ON T3.CODIGO = T1.CODIGO
WHERE T2.COD_PRODUCTO LIKE 'H%'




--Elaborar un reporte  de clientes con cuentas de ahorro  por rango de edad (<18,18-25, 26-35, 36-40, 41-50,51-65,65+ años), 
--mostrando el saldo total y el promedio en sus cuentas de ahorro.

-- 1° 
SELECT * FROM [dbo].[TB_CLIENTE_PERFIL]
SELECT * FROM [dbo].[TB_CLIENTE_PRODUCTOS]

SELECT 
CASE 
	WHEN DATEDIFF(YEAR,A.FH_NACIMIENTO,GETDATE())<18  THEN '< 18 AÑOS'
	WHEN DATEDIFF(YEAR,A.FH_NACIMIENTO,GETDATE())<=25 THEN '<= 25 AÑOS'
	WHEN DATEDIFF(YEAR,A.FH_NACIMIENTO,GETDATE())<=35 THEN '<= 35 AÑOS'
	WHEN DATEDIFF(YEAR,A.FH_NACIMIENTO,GETDATE())<=40 THEN '<= 40 AÑOS'
	WHEN DATEDIFF(YEAR,A.FH_NACIMIENTO,GETDATE())<=50 THEN '<= 50 AÑOS'
	WHEN DATEDIFF(YEAR,A.FH_NACIMIENTO,GETDATE())<=65 THEN '<= 65 AÑOS'
ELSE '> 65 AÑOS' END SEGMENTACION, COUNT(A.CODIGO) AS CLIENTES, SUM(B.SALDO_AHORRO) AS SALDO, AVG(B.SALDO_AHORRO) AS PROMEDIO
FROM [dbo].[TB_CLIENTE_PERFIL] A
INNER JOIN [dbo].[TB_CLIENTE_PRODUCTOS] B ON A.CODIGO = b.CODIGO
WHERE B.CTA_AHORRO > 0
GROUP BY 
CASE 
	WHEN DATEDIFF(YEAR,A.FH_NACIMIENTO,GETDATE())<18  THEN '< 18 AÑOS'
	WHEN DATEDIFF(YEAR,A.FH_NACIMIENTO,GETDATE())<=25 THEN '<= 25 AÑOS'
	WHEN DATEDIFF(YEAR,A.FH_NACIMIENTO,GETDATE())<=35 THEN '<= 35 AÑOS'
	WHEN DATEDIFF(YEAR,A.FH_NACIMIENTO,GETDATE())<=40 THEN '<= 40 AÑOS'
	WHEN DATEDIFF(YEAR,A.FH_NACIMIENTO,GETDATE())<=50 THEN '<= 50 AÑOS'
	WHEN DATEDIFF(YEAR,A.FH_NACIMIENTO,GETDATE())<=65 THEN '<= 65 AÑOS'
ELSE '> 65 AÑOS' END



--Elaborar una tabla que nos muestre a todos los clientes del banco, por segmento, edad, ingreso
-- y la tenencia de los productos pasivos ( ahorro, plazo, CTS) y activos (tarjeta, préstamo consumo y hipotecario).

SELECT A.CODIGO,A.COD_SEGMENTO,DATEDIFF(YEAR,A.FH_NACIMIENTO,GETDATE()) AS EDAD,A.INGRESO, B.CTA_AHORRO,B.CTA_PLAZO,B.CTA_CTS,B.CTA_TARJETA,B.CTA_PRESTAMO,B.CTA_HIPOTECARIO
INTO TB_CLIENTE_PRODUCTO
FROM [dbo].[TB_CLIENTE_PERFIL] A
LEFT JOIN [dbo].[TB_CLIENTE_PRODUCTOS] B ON A.CODIGO = B.CODIGO

SELECT * FROM [dbo].[TB_CLIENTE_PRODUCTO]

--Se necesita un reporte de clientes tarjeta de crédito por  rango de ingreso (0-2.5M, 2.5M-3.5M, 3.5M-7M, 7M +), 
-- mostrando el numero de clientes, saldo y promedio de la tarjeta.
use BANCO
SELECT * FROM TB_CLIENTE_PERFIL
SELECT * FROM [dbo].[TB_CLIENTE_PRESTAMOS]
SELECT * FROM [dbo].[TB_CLIENTE_PRODUCTOS]


SELECT 
CASE WHEN INGRESO = 0 THEN '
FROM [dbo].[TB_CLIENTE_PERFIL] A
INNER JOIN [dbo].[TB_CLIENTE_PRODUCTOS] B ON A.CODIGO = B.CODIGO
WHERE B.CTA_TARJETA > 0